// Package manifest loads and validates HADO manifests.
//
// Reference YAML (docs/hado.manifest.reference.yaml) is generated by WriteManifestReferenceYAML;
// per-field descriptions are in field_docs.go.
package manifest
